name: Deploy Private Chat Company

on:
  push:
    branches:
      - company

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: nevojt/private_company:latest

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD_COMPANY }}
        SSH_HOST: ${{ secrets.SSH_HOST_COMPANY }}
        SSH_USER: ${{ secrets.SSH_USER_COMPANY }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        docker pull nevojt/private_company:latest && \
        docker stop private_company || true && \
        docker rm private_company || true && \
        docker run -d --name private_company -p 8080:8080 nevojt/private_company:latest"
